name: Deploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: list files
      run: ls -a

    - name: current directory
      run: pwd

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: install req
      run: pip install -r req.txt 

    - name: Run script
      run: python retry.py 
      env:
        VERSION_TAG: ${{ github.ref_name }}


      

        